// READ MODE THEMES - LIGHT & DARK

export const SET_READ_MODE_LIGHT = "SET_READ_MODE_LIGHT";
export const SET_READ_MODE_DARK = "SET_READ_MODE_DARK";

// REGISTER MODAL OPEN STATE

export const SET_REGISTER_MODAL_OPEN = "SET_REGISTER_MODAL_OPEN";
export const SET_REGISTER_MODAL_CLOSE = "SET_REGISTER_MODAL_CLOSE";

// CHAPTERS

export const GET_ALL_CHAPTERS = "GET_ALL_CHAPTERS";

// BOOKS

export const GET_ALL_BOOKS = "GET_ALL_BOOKS";
export const GET_ACTIVE_EDIT_BOOK = "GET_ACTIVE_EDIT_BOOK";

// USER

export const GET_USER_DETAILS = "GET_USER_DETAILS";
export const PATCH_USER_DETAILS = "PATCH_USER_DETAILS";