const genres = [
    "Action",
    "Adventure",
    "Biography",
    "Classic",
    "Comedy",
    "Crime",
    "Drama",
    "Epic",
    "Fable",
    "Fairy tale",
    "Fantasy",
    "Folk tale",
    "Gothic fiction",
    "Historical",
    "Historical fiction",
    "Horror",
    "Humour",
    "Legend",
    "Magical realism",
    "Memoir",
    "Mystery",
    "Mythology",
    "Paranoid fiction",
    "Philosophical",
    "Political",
    "Romance",
    "Saga",
    "Satire",
    "Sci-Fi",
    "Self-Help",
    "Self improvement",
    "Short story",
    "Social",
    "Speculative",
    "Thriller",
    "Tragicomedy",
    "True Crime",
    "Urban",
    "Western",
];

export default genres;